language: go

go:
  - 1.9
  - '1.10'

install:
  - go get github.com/andrew-d/isbinary
  - go get github.com/fatih/color
  - go get github.com/y-yagi/configure
  - go get -u github.com/golang/lint/golint

before_script:
  - go vet
  - golint
